package Interface;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
import Control.TelaPrincipal_C;
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
     TelaPrincipal_C listener = new TelaPrincipal_C(this);
    
    public TelaPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuRapido = new javax.swing.JPanel();
        CadastrarCliente = new javax.swing.JButton();
        CadastrarProduto = new javax.swing.JButton();
        RealizarVenda = new javax.swing.JButton();
        SAC = new javax.swing.JButton();
        FinalizarProduto = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        UsuarioT = new javax.swing.JMenu();
        FinalizarProgramaT = new javax.swing.JMenuItem();
        CadastroT = new javax.swing.JMenu();
        CadastroClienteT = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1Vendedor = new javax.swing.JMenuItem();
        Administrador_F = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        VendaT = new javax.swing.JMenu();
        VendaRealizarT = new javax.swing.JMenuItem();
        VendaConsultarT = new javax.swing.JMenuItem();
        AjudaT = new javax.swing.JMenu();
        AjudaSobre = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        SACmensagem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuRapido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu Rapido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        MenuRapido.setToolTipText("");

        CadastrarCliente.setText("Cadastrar_Cliente");
        CadastrarCliente.addActionListener(listener);
        CadastrarCliente.setActionCommand("cadastrarCliente");
        CadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarClienteActionPerformed(evt);
            }
        });

        CadastrarProduto.addActionListener(listener);
        CadastrarProduto.setText("Cadastrar_Produto");
        CadastrarProduto.setActionCommand("cadastrar_Produto");
        CadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProdutoActionPerformed(evt);
            }
        });

        RealizarVenda.addActionListener(listener);
        RealizarVenda.setText("Realizar_Venda");
        RealizarVenda.setActionCommand("realizar_Venda");
        RealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarVendaActionPerformed(evt);
            }
        });

        SAC.addActionListener(listener);
        SAC.setText("SAC");
        SAC.setActionCommand("saaC");
        SAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SACActionPerformed(evt);
            }
        });

        FinalizarProduto.addActionListener(listener);
        FinalizarProduto.setText("Filanizar o Programa");
        FinalizarProduto.setActionCommand("filanizar");
        FinalizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuRapidoLayout = new javax.swing.GroupLayout(MenuRapido);
        MenuRapido.setLayout(MenuRapidoLayout);
        MenuRapidoLayout.setHorizontalGroup(
            MenuRapidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuRapidoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(MenuRapidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RealizarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CadastrarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(CadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FinalizarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(SAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        MenuRapidoLayout.setVerticalGroup(
            MenuRapidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuRapidoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(CadastrarCliente)
                .addGap(27, 27, 27)
                .addComponent(CadastrarProduto)
                .addGap(18, 18, 18)
                .addComponent(RealizarVenda)
                .addGap(28, 28, 28)
                .addComponent(SAC)
                .addGap(18, 18, 18)
                .addComponent(FinalizarProduto)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        UsuarioT.setText("Usuario");
        UsuarioT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTActionPerformed(evt);
            }
        });

        FinalizarProgramaT.setText("Finalizar Programa");
        FinalizarProgramaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarProgramaTActionPerformed(evt);
            }
        });
        UsuarioT.add(FinalizarProgramaT);

        jMenuBar1.add(UsuarioT);

        CadastroT.setText("Cadastrar");
        /*
        CadastroT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroTActionPerformed(evt);
            }
        });
        */

        CadastroClienteT.addActionListener(listener);
        CadastroClienteT.setText("Cliente");
        CadastroClienteT.setActionCommand("cliente");
        CadastroClienteT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteTActionPerformed(evt);
            }
        });
        CadastroT.add(CadastroClienteT);

        jMenu6.setText("Funcionario");

        jMenuItem1Vendedor.setText("Vendedorr");
        jMenuItem1Vendedor.setActionCommand("vendedorr");
        jMenuItem1Vendedor.addActionListener(listener);
        jMenuItem1Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1VendedorActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1Vendedor);

        Administrador_F.addActionListener(listener);
        Administrador_F.setText("Administrador");
        Administrador_F.setActionCommand("administrador");
        Administrador_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Administrador_FActionPerformed(evt);
            }
        });
        jMenu6.add(Administrador_F);

        CadastroT.add(jMenu6);

        jMenuItem1.addActionListener(listener);
        jMenuItem1.setActionCommand("computador");
        jMenuItem1.setText("Computador");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        CadastroT.add(jMenuItem1);

        jMenuBar1.add(CadastroT);

        VendaT.setText("Venda");

        VendaRealizarT.setText("RealizarVenda");
        VendaRealizarT.addActionListener(listener);
        VendaRealizarT.setActionCommand("realizarVenda");
        VendaRealizarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendaRealizarTActionPerformed(evt);
            }
        });
        VendaT.add(VendaRealizarT);

        VendaConsultarT.setText("Consultar");
        VendaConsultarT.addActionListener(listener);
        VendaConsultarT.setActionCommand("consultar");
        VendaConsultarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendaConsultarTActionPerformed(evt);
            }
        });
        VendaT.add(VendaConsultarT);

        jMenuBar1.add(VendaT);

        AjudaT.setText("Ajuda");
        AjudaT.addActionListener(listener);
        AjudaT.setActionCommand("ajuda");

        AjudaSobre.setText("SOBRE");
        AjudaSobre.addActionListener(listener);
        AjudaSobre.setActionCommand("sobre");
        AjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjudaSobreActionPerformed(evt);
            }
        });
        AjudaT.add(AjudaSobre);

        jMenuBar1.add(AjudaT);

        jMenu1.setText("SAC");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        SACmensagem.setText("Mensagem");
        SACmensagem.addActionListener(listener);
        SACmensagem.setActionCommand("mensagem");
        SACmensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SACmensagemActionPerformed(evt);
            }
        });
        jMenu1.add(SACmensagem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuRapido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(MenuRapido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(989, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FinalizarProgramaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarProgramaTActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_FinalizarProgramaTActionPerformed

    private void CadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarClienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CadastrarClienteActionPerformed

    private void CadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProdutoActionPerformed
        
    }//GEN-LAST:event_CadastrarProdutoActionPerformed

    private void SACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SACActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_SACActionPerformed

    private void FinalizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarProdutoActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_FinalizarProdutoActionPerformed

    private void CadastroTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroTActionPerformed

    private void CadastroClienteTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroClienteTActionPerformed

    private void VendaRealizarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendaRealizarTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VendaRealizarTActionPerformed

    private void VendaConsultarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendaConsultarTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VendaConsultarTActionPerformed

    private void jMenuItem1VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1VendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1VendedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void AjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjudaSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AjudaSobreActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void SACmensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SACmensagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SACmensagemActionPerformed

    private void RealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarVendaActionPerformed

    }//GEN-LAST:event_RealizarVendaActionPerformed

    private void Administrador_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Administrador_FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Administrador_FActionPerformed

    private void UsuarioTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Administrador_F;
    private javax.swing.JMenuItem AjudaSobre;
    private javax.swing.JMenu AjudaT;
    private javax.swing.JButton CadastrarCliente;
    private javax.swing.JButton CadastrarProduto;
    private javax.swing.JMenuItem CadastroClienteT;
    private javax.swing.JMenu CadastroT;
    private javax.swing.JButton FinalizarProduto;
    private javax.swing.JMenuItem FinalizarProgramaT;
    private javax.swing.JPanel MenuRapido;
    private javax.swing.JButton RealizarVenda;
    private javax.swing.JButton SAC;
    private javax.swing.JMenuItem SACmensagem;
    private javax.swing.JMenu UsuarioT;
    private javax.swing.JMenuItem VendaConsultarT;
    private javax.swing.JMenuItem VendaRealizarT;
    private javax.swing.JMenu VendaT;
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem1Vendedor;
    // End of variables declaration//GEN-END:variables
}
