/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import gerenciamento.dao.FuncionarioDAO;
import gerenciamento.modelo.Funcionario;

/**
 *
 * @author aminathamiguel
 */
public class CadastroFuncionario extends javax.swing.JInternalFrame {

    Funcionario func = new Funcionario();
    FuncionarioDAO funcionario = new FuncionarioDAO();

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        usuarioFunc = new javax.swing.JTextField();
        senhaFunc = new javax.swing.JPasswordField();
        confirmarSenha = new javax.swing.JPasswordField();
        Tipo = new javax.swing.JLabel();
        tipoFunc = new javax.swing.JComboBox<>();
        novoFunc = new javax.swing.JButton();
        cadastrarFunc = new javax.swing.JButton();
        excluirFunc = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        buscarFunc = new javax.swing.JButton();
        pesquisarBusca = new javax.swing.JTextField();

        setTitle("Cadastro de Funcionários");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setText("ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 50, 20, 10);

        jLabel2.setText("Usuário:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 80, 60, 20);

        jLabel3.setText("Senha:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 50, 20);

        jLabel4.setText("Confimar Senha:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 120, 110, 20);

        codigo.setEnabled(false);
        jPanel1.add(codigo);
        codigo.setBounds(70, 40, 390, 26);

        usuarioFunc.setEnabled(false);
        jPanel1.add(usuarioFunc);
        usuarioFunc.setBounds(70, 80, 230, 20);

        senhaFunc.setEnabled(false);
        senhaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFuncActionPerformed(evt);
            }
        });
        jPanel1.add(senhaFunc);
        senhaFunc.setBounds(70, 120, 160, 20);

        confirmarSenha.setEnabled(false);
        jPanel1.add(confirmarSenha);
        confirmarSenha.setBounds(360, 120, 140, 20);

        Tipo.setText("Tipo:");
        jPanel1.add(Tipo);
        Tipo.setBounds(330, 80, 40, 20);

        tipoFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adminstrador", "Vendedor" }));
        tipoFunc.setEnabled(false);
        jPanel1.add(tipoFunc);
        tipoFunc.setBounds(370, 80, 130, 20);

        novoFunc.setText("Novo");
        novoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoFuncActionPerformed(evt);
            }
        });
        jPanel1.add(novoFunc);
        novoFunc.setBounds(77, 220, 90, 30);

        cadastrarFunc.setText("Cadastrar");
        cadastrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarFunc);
        cadastrarFunc.setBounds(180, 220, 104, 29);

        excluirFunc.setText("Excluir");
        jPanel1.add(excluirFunc);
        excluirFunc.setBounds(300, 220, 90, 29);

        cancelar.setText("Cancelar");
        jPanel1.add(cancelar);
        cancelar.setBounds(410, 220, 98, 29);

        buscarFunc.setText("Buscar");
        buscarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFuncActionPerformed(evt);
            }
        });
        jPanel1.add(buscarFunc);
        buscarFunc.setBounds(260, 160, 110, 30);
        jPanel1.add(pesquisarBusca);
        pesquisarBusca.setBounds(70, 160, 180, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(548, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void senhaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFuncActionPerformed

    private void novoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoFuncActionPerformed
        // TODO add your handling code here:

        codigo.setEnabled(true);
        usuarioFunc.setEnabled(true);
        senhaFunc.setEnabled(true);
        tipoFunc.setEnabled(true);
    }//GEN-LAST:event_novoFuncActionPerformed

    private void cadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncActionPerformed
        // TODO add your handling code here:
        func.setCodFuncionario(Integer.parseInt(codigo.getText()));
        func.setUsuarioFuncionario(usuarioFunc.getText());
        func.setSenhaFuncionario(senhaFunc.getText());
        func.setTipoFuncionario((String) tipoFunc.getSelectedItem());

        funcionario.Cadastrar(func);

        codigo.setText("");
        usuarioFunc.setText("");
        senhaFunc.setText("");
        confirmarSenha.setText("");

        codigo.setEnabled(false);
        usuarioFunc.setEnabled(false);
        senhaFunc.setEnabled(false);
        confirmarSenha.setEnabled(false);
        tipoFunc.setEnabled(false);
        cadastrarFunc.setEnabled(false);
        cancelar.setEnabled(false);
    }//GEN-LAST:event_cadastrarFuncActionPerformed

    private void buscarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFuncActionPerformed
        // TODO add your handling code here:
        func.setPesquisaFuncionario(usuarioFunc.getText());
        Funcionario f = funcionario.buscaFuncionario(func);
        codigo.setText(String.valueOf(f));//setar o inteiro em string
        usuarioFunc.setText(f.getUsuarioFuncionario());
        senhaFunc.setText(f.getSenhaFuncionario());
        confirmarSenha.setText(f.getSenhaFuncionario());
        tipoFunc.setSelectedItem(f.getTipoFuncionario());
        excluirFunc.setEnabled(true);
    }//GEN-LAST:event_buscarFuncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tipo;
    private javax.swing.JButton buscarFunc;
    private javax.swing.JButton cadastrarFunc;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField codigo;
    private javax.swing.JPasswordField confirmarSenha;
    private javax.swing.JButton excluirFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton novoFunc;
    private javax.swing.JTextField pesquisarBusca;
    private javax.swing.JPasswordField senhaFunc;
    private javax.swing.JComboBox<String> tipoFunc;
    private javax.swing.JTextField usuarioFunc;
    // End of variables declaration//GEN-END:variables
}
