package view;

import gerenciamento.conexao.Conexao;
import view.CadastroAdministrador;
import java.awt.Color;
import static java.awt.SystemColor.menu;

/**
 *
 * @author aminathamiguel
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Conexao conecta = new Conexao();
    CadastroAdministrador cadadmin = new CadastroAdministrador();
    CadastroFuncionario cadfunc = new CadastroFuncionario();
    CadastroCliente cadcliente = new CadastroCliente();
    CadastroComputadores cadcomputador = new CadastroComputadores();
    Sobre sobre = new Sobre();


    CadastroAdministrador cadadm;
    CadastroFuncionario cadfun;
    CadastroCliente cadclient;
    
    CadastroComputadores cadcomp;
    
    public TelaPrincipal() {
        initComponents();
        conecta.conexao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jdprincipal = new javax.swing.JDesktopPane();
        jdbemvindo = new javax.swing.JInternalFrame();
        cadastrarcliente = new javax.swing.JButton();
        cadastrarcomputador = new javax.swing.JButton();
        finalizarprograma = new javax.swing.JButton();
        jLabelFundoBemVindo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        jMenuItemFinalizarPrograma = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        cadastroCliente = new javax.swing.JMenuItem();
        cadastroComputador = new javax.swing.JMenuItem();
        cadastroAdministrador = new javax.swing.JMenuItem();
        cadastroFuncionario = new javax.swing.JMenuItem();
        ferramentas = new javax.swing.JMenu();
        telaBemVindo = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jdprincipal.setLayout(null);

        jdbemvindo.setClosable(true);
        jdbemvindo.setTitle("Bem Vindo");
        jdbemvindo.setToolTipText("");
        jdbemvindo.setVisible(true);
        jdbemvindo.getContentPane().setLayout(null);

        cadastrarcliente.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        cadastrarcliente.setText("Cadastrar Cliente");
        cadastrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarclienteActionPerformed(evt);
            }
        });
        jdbemvindo.getContentPane().add(cadastrarcliente);
        cadastrarcliente.setBounds(200, 110, 210, 35);

        cadastrarcomputador.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        cadastrarcomputador.setText("Cadastrar Computador");
        cadastrarcomputador.setPreferredSize(new java.awt.Dimension(161, 29));
        cadastrarcomputador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarcomputadorActionPerformed(evt);
            }
        });
        jdbemvindo.getContentPane().add(cadastrarcomputador);
        cadastrarcomputador.setBounds(200, 160, 210, 35);

        finalizarprograma.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        finalizarprograma.setText("Finalizar Programa");
        finalizarprograma.setPreferredSize(new java.awt.Dimension(161, 29));
        finalizarprograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarprogramaActionPerformed(evt);
            }
        });
        jdbemvindo.getContentPane().add(finalizarprograma);
        finalizarprograma.setBounds(200, 210, 210, 35);

        jLabelFundoBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ecran-chiffres-binaires.png"))); // NOI18N
        jLabelFundoBemVindo.setLabelFor(jdprincipal);
        jLabelFundoBemVindo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jdbemvindo.getContentPane().add(jLabelFundoBemVindo);
        jLabelFundoBemVindo.setBounds(0, 69, 626, 245);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de:");
        jdbemvindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 23, 209, 28);

        jdprincipal.add(jdbemvindo);
        jdbemvindo.setBounds(20, 90, 650, 360);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdprincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jdprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1300, 750);
        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 750, 0, 0);

        menu.setMaximumSize(new java.awt.Dimension(321, 32768));
        menu.setPreferredSize(new java.awt.Dimension(321, 22));

        menuUsuario.setText("Usuario");

        jMenuItemFinalizarPrograma.setText("Finalizar Programa");
        jMenuItemFinalizarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFinalizarProgramaActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItemFinalizarPrograma);

        menu.add(menuUsuario);

        menuCadastro.setText("Cadastro");
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });

        cadastroCliente.setText("Cliente");
        cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroCliente);

        cadastroComputador.setText("Computador");
        cadastroComputador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroComputadorActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroComputador);

        cadastroAdministrador.setText("Administrador");
        cadastroAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAdministradorActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroAdministrador);

        cadastroFuncionario.setText("Funcionario");
        cadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroFuncionario);

        menu.add(menuCadastro);

        ferramentas.setText("Ferramentas");
        ferramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ferramentasActionPerformed(evt);
            }
        });

        telaBemVindo.setText("Tela Bem-Vindo");
        telaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaBemVindoActionPerformed(evt);
            }
        });
        ferramentas.add(telaBemVindo);

        menu.add(ferramentas);

        menuAjuda.setText("Ajuda");

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(jMenuItemSobre);

        menu.add(menuAjuda);

        setJMenuBar(menu);

        setSize(new java.awt.Dimension(906, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClienteActionPerformed
        // TODO add your handling code here:

        if (cadclient == null) {
            cadclient = new CadastroCliente();
            cadclient.setVisible(true);
            cadclient.setResizable(false);
            jdprincipal.add(cadclient);
        } else {
            cadclient.setVisible(true);
            cadclient.setResizable(false);
        }
    }//GEN-LAST:event_cadastroClienteActionPerformed

    private void jMenuItemFinalizarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFinalizarProgramaActionPerformed
        // TODO add your handling code here:
        conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemFinalizarProgramaActionPerformed

    private void cadastroComputadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroComputadorActionPerformed
        // TODO add your handling code here:
        if (cadcomputador == null) {
            cadcomputador = new CadastroComputadores();
            cadcomputador.setVisible(true);
            cadcomputador.setResizable(false);
            jdprincipal.add(cadcomputador);
        } else {
            cadcomputador.setVisible(true);
            cadcomputador.setResizable(false);
        }
    }//GEN-LAST:event_cadastroComputadorActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        // TODO add your handling code here:
        if (sobre == null) {
            sobre = new Sobre();
            sobre.setVisible(true);
            sobre.setResizable(false);
            jdprincipal.add(sobre);
        }
        sobre.setVisible(true);
        sobre.setResizable(false);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void cadastrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarclienteActionPerformed

    private void cadastrarcomputadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarcomputadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarcomputadorActionPerformed

    private void finalizarprogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarprogramaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_finalizarprogramaActionPerformed

    private void ferramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ferramentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ferramentasActionPerformed

    private void telaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaBemVindoActionPerformed
        // TODO add your handling code here:
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_telaBemVindoActionPerformed

    private void cadastroAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAdministradorActionPerformed
        // TODO add your handling code here:
        if (cadadmin == null) {
            cadadmin = new CadastroAdministrador();
            cadadmin.setVisible(true);
            //cadadmin.setResizable(false);
            jdprincipal.add(cadadmin);
        } else {
            cadadmin.setVisible(true);
            //cadadmin.setResizable(false);
        }
    }//GEN-LAST:event_cadastroAdministradorActionPerformed

    private void cadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroFuncionarioActionPerformed
        // TODO add your handling code here:
        if (cadfunc == null) {
            cadfunc = new CadastroFuncionario();
            cadfunc.setVisible(true);
            cadfunc.setResizable(false);
            jdprincipal.add(cadfunc);
        } else {
            cadfunc.setVisible(true);
            cadfunc.setResizable(false);
        }
    }//GEN-LAST:event_cadastroFuncionarioActionPerformed

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarcliente;
    private javax.swing.JButton cadastrarcomputador;
    private javax.swing.JMenuItem cadastroAdministrador;
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroComputador;
    private javax.swing.JMenuItem cadastroFuncionario;
    private javax.swing.JMenu ferramentas;
    private javax.swing.JButton finalizarprograma;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundoBemVindo;
    private javax.swing.JMenuItem jMenuItemFinalizarPrograma;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JInternalFrame jdbemvindo;
    public javax.swing.JDesktopPane jdprincipal;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenuItem telaBemVindo;
    // End of variables declaration//GEN-END:variables
}
