package view;

import gerenciamento.conexao.Conexao;

import java.awt.Color;
import static java.awt.SystemColor.menu;

/**
 *
 * @author aminathamiguel
 */
public class TelaPrincipal extends javax.swing.JFrame {
    Conexao conecta = new Conexao();
     
    CadastroAdministrador cadadmin;
    CadastroCliente cadcliente;
    
    CadastroComputadores cadcomputador;
    ConsultarVenda cvenda;
    SACMensagem smensagem;
    Sobre sobre;
    Venda venda;
    // Creates new form NossaTelaPrincipal
    //Principal listener = new Principal(this);

    public TelaPrincipal() {
        initComponents();
        conecta.conexao();
        
        getContentPane().setBackground(Color.WHITE);  //YELLOW
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jdprincipal = new javax.swing.JDesktopPane();
        jdbemvindo = new javax.swing.JInternalFrame();
        pesquisarcliente4 = new javax.swing.JButton();
        pesquisarcomputador4 = new javax.swing.JButton();
        cadastrarcliente = new javax.swing.JButton();
        cadastrarcomputador = new javax.swing.JButton();
        realizarvenda = new javax.swing.JButton();
        finalizarprograma = new javax.swing.JButton();
        jLabelFundoBemVindo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        jMenuItemFinalizarPrograma = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        funcionario = new javax.swing.JMenuItem();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemComputadores = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenu();
        jMenuItemRealizar = new javax.swing.JMenuItem();
        jMenuItemConsultar = new javax.swing.JMenuItem();
        telabemvindo = new javax.swing.JMenu();
        jMenuItemMensagens = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdprincipal.setLayout(null);

        jdbemvindo.setClosable(true);
        jdbemvindo.setTitle("Bem Vindo");
        jdbemvindo.setToolTipText("");
        jdbemvindo.setVisible(true);
        jdbemvindo.getContentPane().setLayout(null);

        pesquisarcliente4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pesquisarcliente4.setText("Pesquisar Cliente");
        pesquisarcliente4.setBounds(new java.awt.Rectangle(340, 130, 210, 35));
        pesquisarcliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarcliente4ActionPerformed(evt);
            }
        });
        jdbemvindo.getContentPane().add(pesquisarcliente4);
        pesquisarcliente4.setBounds(340, 130, 210, 35);

        pesquisarcomputador4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pesquisarcomputador4.setText("Pesquisar Computador");
        pesquisarcomputador4.setPreferredSize(new java.awt.Dimension(161, 29));
        pesquisarcomputador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarcomputador4ActionPerformed(evt);
            }
        });
        jdbemvindo.getContentPane().add(pesquisarcomputador4);
        pesquisarcomputador4.setBounds(340, 170, 210, 35);

        cadastrarcliente.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        cadastrarcliente.setText("Cadastrar Cliente");
        cadastrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarclienteActionPerformed(evt);
            }
        });
        jdbemvindo.getContentPane().add(cadastrarcliente);
        cadastrarcliente.setBounds(90, 130, 210, 35);

        cadastrarcomputador.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        cadastrarcomputador.setText("Cadastrar Computador");
        cadastrarcomputador.setPreferredSize(new java.awt.Dimension(161, 29));
        cadastrarcomputador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarcomputadorActionPerformed(evt);
            }
        });
        jdbemvindo.getContentPane().add(cadastrarcomputador);
        cadastrarcomputador.setBounds(90, 170, 210, 35);

        realizarvenda.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        realizarvenda.setText("Realizar Venda");
        realizarvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarvendaActionPerformed(evt);
            }
        });
        jdbemvindo.getContentPane().add(realizarvenda);
        realizarvenda.setBounds(90, 210, 210, 35);

        finalizarprograma.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        finalizarprograma.setText("Finalizar Programa");
        finalizarprograma.setPreferredSize(new java.awt.Dimension(161, 29));
        finalizarprograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarprogramaActionPerformed(evt);
            }
        });
        jdbemvindo.getContentPane().add(finalizarprograma);
        finalizarprograma.setBounds(340, 210, 210, 35);

        jLabelFundoBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ecran-chiffres-binaires.png"))); // NOI18N
        jLabelFundoBemVindo.setLabelFor(jdprincipal);
        jLabelFundoBemVindo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jdbemvindo.getContentPane().add(jLabelFundoBemVindo);
        jLabelFundoBemVindo.setBounds(0, 69, 626, 245);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de:");
        jdbemvindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 23, 209, 28);

        jdprincipal.add(jdbemvindo);
        jdbemvindo.setBounds(20, 90, 650, 360);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdprincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jdprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        menu.setMaximumSize(new java.awt.Dimension(321, 32768));
        menu.setPreferredSize(new java.awt.Dimension(321, 22));

        menuUsuario.setText("Usuario");

        jMenuItemFinalizarPrograma.setText("Finalizar Programa");
        jMenuItemFinalizarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFinalizarProgramaActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItemFinalizarPrograma);

        menu.add(menuUsuario);

        menuCadastro.setText("Cadastro");

        jMenuItem1.setText("Administrador");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuItem1);

        funcionario.setText("Funcionário");
        funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(funcionario);

        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuItemCliente);

        jMenuItemComputadores.setText("Computadores");
        jMenuItemComputadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComputadoresActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuItemComputadores);

        menu.add(menuCadastro);

        menuVenda.setText("Venda");

        jMenuItemRealizar.setText("Realizar");
        jMenuItemRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRealizarActionPerformed(evt);
            }
        });
        menuVenda.add(jMenuItemRealizar);

        jMenuItemConsultar.setText("Consultar");
        jMenuItemConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarActionPerformed(evt);
            }
        });
        menuVenda.add(jMenuItemConsultar);

        menu.add(menuVenda);

        telabemvindo.setText("Ferramentas");

        jMenuItemMensagens.setText("Tela Bem-Vindo");
        jMenuItemMensagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMensagensActionPerformed(evt);
            }
        });
        telabemvindo.add(jMenuItemMensagens);

        menu.add(telabemvindo);

        menuAjuda.setText("Ajuda");

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(jMenuItemSobre);

        menu.add(menuAjuda);

        setJMenuBar(menu);

        setSize(new java.awt.Dimension(906, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        // TODO add your handling code here:
        //CadastroCliente cadacliente = new CadastroCliente();
        //tela.setVisible(true);
        if (cadcliente == null) {
            cadcliente = new CadastroCliente();
            jdprincipal.add(cadcliente);;
        }
        cadcliente.setVisible(true);
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarActionPerformed
        // TODO add your handling code here:
        //cvenda.CadastroConsulVend(ConsultarVenda.getInstancia());
        if (cvenda == null) {
            cvenda = new ConsultarVenda();
            jdprincipal.add(cvenda);
        }
        cvenda.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarActionPerformed

    private void jMenuItemFinalizarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFinalizarProgramaActionPerformed
        // TODO add your handling code here:
        conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemFinalizarProgramaActionPerformed

    private void jMenuItemComputadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComputadoresActionPerformed
        // TODO add your handling code here:
        //cadcomputador.CadastroComp(CadastroComputadores.getInstancia());
        if (cadcomputador == null) {
            cadcomputador = new CadastroComputadores();
            jdprincipal.add(cadcomputador);
        }
        cadcomputador.setVisible(true);
    }//GEN-LAST:event_jMenuItemComputadoresActionPerformed

    private void jMenuItemRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRealizarActionPerformed
        // TODO add your handling code here:
       // venda.Vendas(Venda.getInstancia());
        if (venda == null) {
            venda = new Venda();
            jdprincipal.add(venda);
        }
        venda.setVisible(true);
    }//GEN-LAST:event_jMenuItemRealizarActionPerformed

    private void jMenuItemMensagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMensagensActionPerformed
        // TODO add your handling code here:
       // smensagem.SACMens(SACMensagem.getInstancia());
       TelaPrincipal tela = new TelaPrincipal();
       tela.setVisible(true);
       dispose();
        /*if (smensagem == null) {
            smensagem = new SACMensagem();
            jdprincipal.add(smensagem);;
        }
        smensagem.setVisible(true);*/
    }//GEN-LAST:event_jMenuItemMensagensActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (cadadmin == null) {
            cadadmin = new CadastroAdministrador();
            jdprincipal.add(cadadmin);
        }
        cadadmin.setVisible(true);
        //cadadmin.CadastroAdm(CadastroAdministrador.getInstancia());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        // TODO add your handling code here:
      //  sobreinfo.SobreProgram(Sobre.getInstancia());
        if (sobre == null) {
            sobre = new Sobre();
            jdprincipal.add(sobre);;
        }
        sobre.setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioActionPerformed
        // TODO add your handling code here:
        if (cadadmin == null) {
            cadadmin = new CadastroAdministrador();
            jdprincipal.add(cadadmin);
        }
        cadadmin.setVisible(true);
    }//GEN-LAST:event_funcionarioActionPerformed

    private void pesquisarcliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarcliente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarcliente4ActionPerformed

    private void pesquisarcomputador4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarcomputador4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarcomputador4ActionPerformed

    private void cadastrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarclienteActionPerformed

    private void cadastrarcomputadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarcomputadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarcomputadorActionPerformed

    private void realizarvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarvendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realizarvendaActionPerformed

    private void finalizarprogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarprogramaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_finalizarprogramaActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarcliente;
    private javax.swing.JButton cadastrarcomputador;
    private javax.swing.JButton finalizarprograma;
    private javax.swing.JMenuItem funcionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundoBemVindo;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemComputadores;
    private javax.swing.JMenuItem jMenuItemConsultar;
    private javax.swing.JMenuItem jMenuItemFinalizarPrograma;
    private javax.swing.JMenuItem jMenuItemMensagens;
    private javax.swing.JMenuItem jMenuItemRealizar;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JInternalFrame jdbemvindo;
    public javax.swing.JDesktopPane jdprincipal;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu menuVenda;
    private javax.swing.JButton pesquisarcliente4;
    private javax.swing.JButton pesquisarcomputador4;
    private javax.swing.JButton realizarvenda;
    private javax.swing.JMenu telabemvindo;
    // End of variables declaration//GEN-END:variables
}
